### PR TITLE
chore: typescript complain about missing call signatures

### PR DESCRIPTION
**Pull request by UncleBill**
image

### CODE REVIEW

**Review by suikodev — APPROVED** [review]

**Comment by UncleBill** [comment]
@suikodev Thanks for merging. BTW, can we have a new release on npm? I patched this on our project, if you publish it, We can get rid of the patch. ❤️

**Comment by suikodev** [comment]
First of all, thank you for your pr.

I merged it without testing it beforehand, as I reviewed your code and it appeared to be correct. However, upon testing it on my local machine, the code failed to build. As a result, I made a small update and published a new release, version 1.1.8. I hope your code is compatible with this new version.

**Comment by suikodev** [comment]
If the updated version doesn't run in your environment, feel free to reach out to me anytime : )

**Comment by UncleBill** [comment]
> If the updated version doesn't run in your environment, feel free to reach out to me anytime : )

Thanks. ❤️

**Pull request merged**
